import { supabase } from "@/integrations/supabase/client";
import { createCampaign, createCharacter } from "@/lib/api";
import type { TablesInsert } from "@/integrations/supabase/types";

export const DEMO_CHARACTER_NAME = "Wren Calloway";
export const DEMO_CAMPAIGN_NAME = "Ashfall Expedition";
export const DEMO_PACK = "Core Generic Pack";

/** True when this account already holds the demo set. Keeps seeding idempotent. */
export async function hasDemoContent(): Promise<boolean> {
  const { data, error } = await supabase
    .from("characters")
    .select("id")
    .eq("name", DEMO_CHARACTER_NAME)
    .limit(1);
  if (error) throw new Error(error.message);
  return (data ?? []).length > 0;
}

/**
 * Original, generic demo content. No proprietary trait names, prose or tables.
 * Guarded: calling it twice will not duplicate the demo set.
 */
export async function seedDemoContent(userId: string) {
  if (await hasDemoContent()) return { skipped: true as const };
  const campaign = await createCampaign({

    name: "Ashfall Expedition",
    description:
      "A near-future salvage crew works contract jobs in an evacuated industrial belt. Demo campaign generated by Universal Character Forge.",
    settings: {
      point_limit: 150,
      disadvantage_limit: -50,
      quirk_limit: -5,
      tech_level: 8,
      house_rules: "Campaign uses the default engine formulas. House rules go here.",
      allowed_packs: ["Core Generic Pack"],
    },
  });

  const character = await createCharacter({
    name: "Wren Calloway",
    player_name: "Demo Player",
    concept: "Salvage-crew field medic with a talent for reading city grids",
    campaign_id: campaign.id,
    point_budget: 150,
    tech_level: 8,
    st: 11,
    dx: 12,
    iq: 12,
    ht: 11,
    hp_delta: 1,
    will_delta: 1,
    per_delta: 2,
    fp_delta: 0,
    speed_delta: 0,
    move_delta: 0,
    current_hp: 12,
    current_fp: 11,
    wealth: "Average",
    status: 0,
    approved: true,
    notes: "Demo character. Everything here is editable — treat it as a starting point.",
  });

  const entries: TablesInsert<"character_entries">[] = [
    {
      character_id: character.id,
      kind: "advantage",
      name: "Field Medic",
      category: "Talent",
      points: 10,
      levels: 1,
      notes: "Bonus to stabilising wounded allies under pressure.",
      source: { label: "Core Generic Pack", type: "user" },
    },
    {
      character_id: character.id,
      kind: "advantage",
      name: "Quick Reflexes",
      category: "Physical",
      points: 15,
      levels: 1,
      data: { modifiers: [{ name: "Situational (crisis only)", percent: -20 }] },
      source: { label: "Core Generic Pack", type: "user" },
    },
    {
      character_id: character.id,
      kind: "perk",
      name: "Steady Hands",
      category: "Perk",
      points: 1,
      levels: 1,
    },
    {
      character_id: character.id,
      kind: "disadvantage",
      name: "Duty to Crew",
      category: "Social",
      points: -10,
      levels: 1,
      notes: "Will not abandon a crewmate on contract.",
    },
    {
      character_id: character.id,
      kind: "quirk",
      name: "Narrates repairs out loud",
      category: "Quirk",
      points: -1,
      levels: 1,
    },
    {
      character_id: character.id,
      kind: "skill",
      name: "Urban Navigation",
      category: "Exploration",
      points: 4,
      data: { attribute: "IQ", difficulty: "A", points: 4, defaults: "IQ-5" },
    },
    {
      character_id: character.id,
      kind: "skill",
      name: "Emergency Medicine",
      category: "Medical",
      points: 8,
      data: { attribute: "IQ", difficulty: "H", points: 8, specialization: "Trauma" },
    },
    {
      character_id: character.id,
      kind: "skill",
      name: "Close Combat",
      category: "Combat",
      points: 4,
      data: { attribute: "DX", difficulty: "A", points: 4 },
    },
    {
      character_id: character.id,
      kind: "language",
      name: "Trade Creole",
      category: "Language",
      points: 2,
      data: { spoken: "Accented", written: "Broken" },
    },
    {
      character_id: character.id,
      kind: "equipment",
      name: "Responder Vest",
      category: "Armour",
      data: {
        quantity: 1,
        weight: 8,
        cost: 450,
        carried: true,
        tl: 8,
        legality: "LC4",
        dr: 5,
        locations: ["Torso"],
      },
    },
    {
      character_id: character.id,
      kind: "equipment",
      name: "Utility Baton",
      category: "Weapon",
      data: {
        quantity: 1,
        weight: 2,
        cost: 60,
        carried: true,
        tl: 8,
        legality: "LC4",
        weapons: [
          {
            name: "Swing",
            damage: "sw+1 cr",
            reach: "1",
            parry: "0",
            skill: "Close Combat",
          },
        ],
      },
    },
    {
      character_id: character.id,
      kind: "equipment",
      name: "Crew Sidearm",
      category: "Weapon",
      data: {
        quantity: 1,
        weight: 3,
        cost: 400,
        carried: true,
        tl: 8,
        legality: "LC3",
        weapons: [
          {
            name: "Shot",
            damage: "2d pi",
            accuracy: "2",
            range: "150/1800",
            rof: "3",
            shots: "8",
            bulk: "-2",
            recoil: "2",
            skill: "Close Combat",
          },
        ],
      },
    },
    {
      character_id: character.id,
      kind: "equipment",
      name: "Trauma Kit",
      category: "Gear",
      data: { quantity: 1, weight: 6, cost: 300, carried: true, tl: 8 },
    },

    {
      character_id: character.id,
      kind: "equipment",
      name: "Spare Cell Pack",
      category: "Consumable",
      data: { quantity: 4, weight: 1, cost: 25, carried: false, tl: 8 },
    },
  ];

  const { error } = await supabase.from("character_entries").insert(entries);
  if (error) throw new Error(error.message);

  const library: TablesInsert<"library_entries">[] = [
    {
      owner_id: userId,
      kind: "advantage",
      name: "Field Medic",
      category: "Talent",
      summary: "Training in stabilising casualties away from a clinic.",
      base_points: 10,
      cost_per_level: 10,
      max_levels: 4,
      tags: ["medical", "talent"],
      visibility: "private",
      source_label: DEMO_PACK,
      pack: DEMO_PACK,
      source_type: "user",
    },
    {
      owner_id: userId,
      kind: "advantage",
      name: "Quick Reflexes",
      category: "Physical",
      summary: "Reacts faster than most when a situation turns.",
      base_points: 15,
      cost_per_level: 0,
      tags: ["physical"],
      visibility: "private",
      source_label: DEMO_PACK,
      pack: DEMO_PACK,
      source_type: "user",
    },
    {
      owner_id: userId,
      kind: "skill",
      name: "Urban Navigation",
      category: "Exploration",
      summary: "Finding routes through dense built environments.",
      base_points: 0,
      data: { attribute: "IQ", difficulty: "A", defaults: "IQ-5" },
      tags: ["exploration"],
      visibility: "private",
      source_label: DEMO_PACK,
      pack: DEMO_PACK,
      source_type: "user",
    },
    {
      owner_id: userId,
      kind: "disadvantage",
      name: "Duty to Crew",
      category: "Social",
      summary: "Obligation to a specific group of people.",
      base_points: -10,
      tags: ["social"],
      visibility: "private",
      source_label: DEMO_PACK,
      pack: DEMO_PACK,
      source_type: "user",
    },
    {
      owner_id: userId,
      kind: "equipment",
      name: "Responder Vest",
      category: "Armour",
      summary: "Light protective vest issued to emergency crews.",
      data: { weight: 8, cost: 450, tl: 8, legality: "LC4", dr: 5, locations: ["Torso"] },
      tags: ["armour"],
      visibility: "private",
      source_label: DEMO_PACK,
      pack: DEMO_PACK,
      source_type: "user",
    },
  ];
  await supabase.from("library_entries").insert(library);

  await supabase.from("campaign_notes").insert([
    {
      campaign_id: campaign.id,
      author_id: userId,
      kind: "session",
      title: "Session 0 — Contract briefing",
      body: "The crew signs on for a three-week salvage window. Establish debts, contacts and one complication each.",
    },
    {
      campaign_id: campaign.id,
      author_id: userId,
      kind: "rule",
      title: "House rule: recovery",
      body: "Recovery between contracts is abstracted. Adjust in campaign settings at any time.",
    },
  ]);

  return { skipped: false as const, campaignId: campaign.id, characterId: character.id };
}
