/**
 * Universal entity model configuration.
 * Every campaign object is an `entities` row with a `kind`. Common queryable
 * columns are normalized (name, status, visibility, parent, tags, image);
 * kind-specific narrative fields live in `data` and are declared here so list
 * and detail screens are generated consistently.
 */

export type FieldType = "text" | "textarea" | "list" | "select";

export interface FieldDef {
  key: string;
  label: string;
  type: FieldType;
  gm?: boolean;
  options?: string[];
  placeholder?: string;
}

export interface KindDef {
  kind: string;
  label: string;
  plural: string;
  icon: string;
  group: "world" | "story" | "play" | "assets";
  statuses: string[];
  defaultStatus: string;
  fields: FieldDef[];
  nestable?: boolean;
}

const t = (key: string, label: string, gm = false): FieldDef => ({ key, label, type: "text", gm });
const ta = (key: string, label: string, gm = false): FieldDef => ({
  key,
  label,
  type: "textarea",
  gm,
});
const li = (key: string, label: string, gm = false): FieldDef => ({ key, label, type: "list", gm });

export const KINDS: KindDef[] = [
  {
    kind: "NPC",
    label: "NPC",
    plural: "NPCs",
    icon: "Users",
    group: "world",
    statuses: ["Alive", "Dead", "Missing", "Unknown", "Captured", "Retired"],
    defaultStatus: "Alive",
    fields: [
      t("pronouns", "Pronouns"),
      t("age", "Age"),
      t("species", "Species / type"),
      t("occupation", "Occupation"),
      t("role", "Campaign role"),
      t("title", "Rank / title"),
      ta("appearance", "Appearance"),
      t("voice", "Voice"),
      t("speech", "Speech pattern"),
      li("mannerisms", "Mannerisms"),
      ta("personality", "Personality"),
      li("values", "Values"),
      li("flaws", "Flaws"),
      ta("motivations", "Motivations"),
      t("immediate_goal", "Immediate goal"),
      t("long_goal", "Long-term goal"),
      li("fears", "Fears"),
      ta("biography", "Biography"),
      ta("knowledge", "What they know", true),
      ta("secrets", "Secrets", true),
      li("possessions", "Possessions"),
      ta("influence", "Resources & influence"),
    ],
  },
  {
    kind: "PC",
    label: "Player Character",
    plural: "Player Characters",
    icon: "Shield",
    group: "world",
    statuses: ["Active", "Retired", "Dead", "Missing"],
    defaultStatus: "Active",
    fields: [
      t("player", "Player"),
      t("concept", "Concept"),
      ta("biography", "Biography"),
      ta("appearance", "Appearance"),
      ta("personality", "Personality"),
      li("beliefs", "Beliefs"),
      li("goals", "Goals"),
      li("fears", "Fears"),
      li("bonds", "Bonds"),
      li("flaws", "Flaws"),
      li("possessions", "Important possessions"),
      ta("personal_quests", "Personal quests"),
      ta("discovered_lore", "Discovered lore"),
      ta("player_notes", "Private player notes"),
      ta("gm_notes_pc", "Private GM notes", true),
      ta("system_notes", "System notes (freeform, not interpreted)"),
    ],
  },
  {
    kind: "FACTION",
    label: "Faction",
    plural: "Factions",
    icon: "Flag",
    group: "world",
    statuses: ["Active", "Dormant", "Destroyed", "Ascendant", "Fractured"],
    defaultStatus: "Active",
    fields: [
      t("leader", "Leader"),
      t("headquarters", "Headquarters"),
      t("territory", "Territory"),
      li("values", "Values"),
      li("goals", "Goals"),
      ta("methods", "Methods"),
      ta("resources", "Resources"),
      t("reputation", "Reputation"),
      t("influence", "Influence"),
      ta("current_plans", "Current plans", true),
      ta("secret_agenda", "Secret agenda", true),
    ],
  },
  {
    kind: "LOCATION",
    label: "Location",
    plural: "Locations",
    icon: "MapPin",
    group: "world",
    nestable: true,
    statuses: ["Intact", "Damaged", "Destroyed", "Abandoned", "Hidden"],
    defaultStatus: "Intact",
    fields: [
      {
        key: "location_type",
        label: "Location type",
        type: "select",
        options: [
          "World",
          "Continent",
          "Region",
          "Nation",
          "Province",
          "City",
          "Town",
          "Village",
          "District",
          "Building",
          "Room",
          "Dungeon",
          "Wilderness",
          "Ruin",
          "Point of Interest",
        ],
      },
      ta("sensory", "Sensory details"),
      ta("history", "History"),
      t("population", "Population notes"),
      t("government", "Government"),
      t("economy", "Economy"),
      li("rumors", "Rumors"),
      ta("secrets", "Secrets", true),
    ],
  },
  {
    kind: "ITEM",
    label: "Item",
    plural: "Items",
    icon: "Gem",
    group: "world",
    statuses: ["Available", "Held", "Lost", "Destroyed", "Hidden"],
    defaultStatus: "Available",
    fields: [
      t("category", "Category"),
      ta("significance", "Narrative significance"),
      t("owner", "Current owner"),
      li("previous_owners", "Previous owners"),
      t("current_location", "Current location"),
      ta("history", "History"),
      ta("properties", "Descriptive properties"),
      ta("secrets", "Secrets", true),
    ],
  },
  {
    kind: "CREATURE",
    label: "Creature",
    plural: "Creatures",
    icon: "PawPrint",
    group: "world",
    statuses: ["Extant", "Rare", "Extinct", "Legendary"],
    defaultStatus: "Extant",
    fields: [
      t("habitat", "Habitat"),
      ta("behaviour", "Behaviour"),
      ta("lore", "Lore"),
      li("signs", "Signs of presence"),
      ta("secrets", "Secrets", true),
    ],
  },
  {
    kind: "LORE",
    label: "World Bible Entry",
    plural: "World Bible",
    icon: "BookOpen",
    group: "world",
    nestable: true,
    statuses: ["Draft", "Canon", "Contested"],
    defaultStatus: "Canon",
    fields: [
      {
        key: "category",
        label: "Category",
        type: "select",
        options: [
          "Overview",
          "Cosmology",
          "Geography",
          "History",
          "Culture",
          "Language",
          "Religion",
          "Deity",
          "Government",
          "Politics",
          "Economy",
          "Technology",
          "Supernatural",
          "Organization",
          "Legend",
          "Rumor",
          "Flora & Fauna",
          "Custom",
        ],
      },
      ta("secrets", "GM secrets", true),
    ],
  },
  {
    kind: "ARC",
    label: "Story Arc",
    plural: "Story Arcs",
    icon: "Waypoints",
    group: "story",
    statuses: ["Planned", "Active", "Resolved", "Abandoned"],
    defaultStatus: "Planned",
    fields: [
      ta("dramatic_question", "Dramatic question"),
      li("themes", "Themes"),
      ta("opposition", "Opposition"),
      ta("starting_situation", "Starting situation"),
      ta("escalation", "Escalation"),
      li("turning_points", "Turning points"),
      ta("climax", "Climax", true),
      li("possible_endings", "Possible endings", true),
      ta("consequences", "Consequences", true),
    ],
  },
  {
    kind: "ADVENTURE",
    label: "Adventure",
    plural: "Adventures",
    icon: "Swords",
    group: "story",
    nestable: true,
    statuses: ["Planned", "Active", "Completed", "Shelved"],
    defaultStatus: "Planned",
    fields: [
      ta("hook", "Hook"),
      t("expected_sessions", "Expected sessions"),
      li("objectives", "Objectives"),
      ta("opposition", "Opposition"),
      li("branching", "Branching outcomes", true),
      ta("gm_guidance", "GM guidance", true),
    ],
  },
  {
    kind: "CHAPTER",
    label: "Chapter",
    plural: "Chapters",
    icon: "BookMarked",
    group: "story",
    nestable: true,
    statuses: ["Planned", "Active", "Completed"],
    defaultStatus: "Planned",
    fields: [ta("goal", "Chapter goal"), ta("gm_guidance", "GM guidance", true)],
  },
  {
    kind: "SCENE",
    label: "Scene",
    plural: "Scenes",
    icon: "Clapperboard",
    group: "story",
    nestable: true,
    statuses: ["Planned", "Ready", "Played", "Skipped"],
    defaultStatus: "Planned",
    fields: [
      {
        key: "scene_type",
        label: "Encounter type",
        type: "select",
        options: [
          "Confrontation",
          "Social",
          "Exploration",
          "Puzzle",
          "Hazard",
          "Chase",
          "Investigation",
          "Travel",
          "Downtime",
          "Infiltration",
          "Discovery",
          "Negotiation",
          "Custom",
        ],
      },
      ta("purpose", "Purpose"),
      ta("setup", "Setup"),
      ta("sensory", "Sensory description"),
      ta("read_aloud", "Read-aloud text"),
      ta("gm_info", "GM information", true),
      li("expected_questions", "Expected questions"),
      li("approaches", "Possible approaches"),
      ta("consequences", "Consequences", true),
      li("transitions", "Transitions"),
    ],
  },
  {
    kind: "QUEST",
    label: "Quest",
    plural: "Quests",
    icon: "ScrollText",
    group: "story",
    statuses: ["RUMORED", "AVAILABLE", "ACTIVE", "COMPLETED", "FAILED", "ABANDONED", "EXPIRED"],
    defaultStatus: "AVAILABLE",
    fields: [
      t("giver", "Quest giver"),
      li("objectives", "Objectives"),
      li("optional_objectives", "Optional objectives"),
      li("stages", "Stages"),
      ta("requirements", "Requirements"),
      ta("rewards", "Narrative rewards"),
      ta("consequences", "Consequences", true),
      li("hidden_objectives", "Hidden objectives", true),
      t("expiration", "Expires on"),
    ],
  },
  {
    kind: "MYSTERY",
    label: "Mystery",
    plural: "Mysteries",
    icon: "Search",
    group: "story",
    statuses: ["Open", "Partially solved", "Solved", "Cold"],
    defaultStatus: "Open",
    fields: [
      ta("central_question", "Central question"),
      ta("truth", "Canonical truth", true),
      li("suspects", "Suspects"),
      li("motives", "Motives"),
      li("false_leads", "False leads", true),
      li("revelations", "Revelations", true),
    ],
  },
  {
    kind: "CLUE",
    label: "Clue",
    plural: "Clues",
    icon: "Fingerprint",
    group: "story",
    statuses: ["Undiscovered", "Discovered", "Misread"],
    defaultStatus: "Undiscovered",
    fields: [
      ta("information", "Information revealed"),
      t("source", "Source"),
      t("clue_location", "Where it is found"),
      t("reliability", "Reliability"),
      t("misleading", "Misleading? (yes/no)"),
      ta("gm_interpretation", "GM interpretation", true),
      ta("player_interpretation", "Player interpretation"),
      t("discovered_session", "Discovered in session"),
    ],
  },
  {
    kind: "SECRET",
    label: "Secret",
    plural: "Secrets",
    icon: "EyeOff",
    group: "story",
    statuses: ["Hidden", "Suspected", "Revealed"],
    defaultStatus: "Hidden",
    fields: [
      ta("truth", "Canonical truth", true),
      li("who_knows", "Who knows"),
      li("who_suspects", "Who suspects"),
      li("false_belief", "Who believes something else"),
      ta("reveal_conditions", "Reveal conditions", true),
    ],
  },
  {
    kind: "THREAD",
    label: "Story Thread",
    plural: "Story Threads",
    icon: "GitBranch",
    group: "story",
    statuses: ["Open", "Advancing", "Stalled", "Resolved"],
    defaultStatus: "Open",
    fields: [
      { key: "priority", label: "Priority", type: "select", options: ["Low", "Medium", "High"] },
      t("created_session", "Created in session"),
      t("last_touched", "Last touched session"),
    ],
  },
  {
    kind: "CLOCK",
    label: "Campaign Clock",
    plural: "Clocks",
    icon: "Timer",
    group: "story",
    statuses: ["Ticking", "Paused", "Triggered"],
    defaultStatus: "Ticking",
    fields: [
      t("segments", "Segments"),
      t("progress", "Progress"),
      ta("trigger", "Trigger"),
      ta("consequence", "Consequence", true),
    ],
  },
  {
    kind: "HANDOUT",
    label: "Handout",
    plural: "Handouts",
    icon: "FileText",
    group: "assets",
    statuses: ["Draft", "Ready", "Revealed"],
    defaultStatus: "Draft",
    fields: [
      {
        key: "handout_type",
        label: "Type",
        type: "select",
        options: [
          "Letter",
          "Journal",
          "Wanted poster",
          "Newspaper",
          "Contract",
          "Prophecy",
          "Menu",
          "Coded message",
          "Diagram",
          "Photograph",
          "Clipping",
          "Government document",
          "Scroll",
          "Book",
          "Research notes",
          "Receipt",
          "Ticket",
          "Custom",
        ],
      },
      ta("body", "Player-safe content"),
      ta("gm_original", "GM original / true content", true),
      t("source", "Source"),
    ],
  },
  {
    kind: "CUSTOM",
    label: "Custom Entity",
    plural: "Custom Entities",
    icon: "Boxes",
    group: "world",
    statuses: ["Active", "Archived"],
    defaultStatus: "Active",
    fields: [t("custom_type", "Type")],
  },
];

export const KIND_MAP: Record<string, KindDef> = Object.fromEntries(KINDS.map((k) => [k.kind, k]));

export function kindDef(kind: string): KindDef {
  return KIND_MAP[kind] ?? KIND_MAP["CUSTOM"]!;
}

export const VISIBILITIES = [
  { value: "GM_ONLY", label: "GM only" },
  { value: "UNREVEALED", label: "Unrevealed" },
  { value: "SELECTED_PLAYERS", label: "Selected players" },
  { value: "ALL_PLAYERS", label: "All players" },
  { value: "PUBLIC", label: "Public" },
] as const;

export const PLAYER_VISIBLE = ["ALL_PLAYERS", "PUBLIC"];

export const RELATIONSHIP_TYPES = [
  "MEMBER_OF",
  "LEADS",
  "ENEMY_OF",
  "ALLY_OF",
  "PARENT_OF",
  "CHILD_OF",
  "SIBLING_OF",
  "LOVES",
  "HATES",
  "OWES",
  "CONTROLS",
  "SERVES",
  "RULES",
  "LOCATED_IN",
  "BASED_IN",
  "OWNS",
  "KNOWS",
  "WANTS",
  "FEARS",
  "TRUSTS",
  "BETRAYED",
  "CREATED_BY",
  "DESTROYED_BY",
  "WORSHIPS",
  "INVESTIGATES",
  "WORKS_FOR",
  "SECRETLY_WORKS_FOR",
  "CONNECTED_TO",
];
