/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known/oauth-protected-resource'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedOauthConsentRouteImport } from './routes/_authenticated/oauth-consent'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated/campaigns.index'
import { Route as AuthenticatedCampaignsIdRouteImport } from './routes/_authenticated/campaigns.$id'
import { Route as AuthenticatedCharactersIndexRouteImport } from './routes/_authenticated/characters.index'
import { Route as AuthenticatedCharactersIdRouteImport } from './routes/_authenticated/characters.$id'
import { Route as AuthenticatedEntitiesIdRouteImport } from './routes/_authenticated/entities.$id'
import { Route as AuthenticatedPacksIndexRouteImport } from './routes/_authenticated/packs.index'
import { Route as AuthenticatedPacksPackRouteImport } from './routes/_authenticated/packs.$pack'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'
import { Route as ApiPublicVersionRouteImport } from './routes/api/public/version'
import { Route as ApiPublicOauthAuthorizeRouteImport } from './routes/api/public/oauth/authorize'
import { Route as ApiPublicOauthRegisterRouteImport } from './routes/api/public/oauth/register'
import { Route as ApiPublicOauthTokenRouteImport } from './routes/api/public/oauth/token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOauthConsentRoute =
  AuthenticatedOauthConsentRouteImport.update({
    id: '/oauth-consent',
    path: '/oauth-consent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsIdRoute =
  AuthenticatedCampaignsIdRouteImport.update({
    id: '/campaigns/$id',
    path: '/campaigns/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCharactersIndexRoute =
  AuthenticatedCharactersIndexRouteImport.update({
    id: '/characters/',
    path: '/characters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCharactersIdRoute =
  AuthenticatedCharactersIdRouteImport.update({
    id: '/characters/$id',
    path: '/characters/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntitiesIdRoute = AuthenticatedEntitiesIdRouteImport.update({
  id: '/entities/$id',
  path: '/entities/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPacksIndexRoute = AuthenticatedPacksIndexRouteImport.update({
  id: '/packs/',
  path: '/packs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPacksPackRoute = AuthenticatedPacksPackRouteImport.update({
  id: '/packs/$pack',
  path: '/packs/$pack',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVersionRoute = ApiPublicVersionRouteImport.update({
  id: '/api/public/version',
  path: '/api/public/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthAuthorizeRoute = ApiPublicOauthAuthorizeRouteImport.update({
  id: '/api/public/oauth/authorize',
  path: '/api/public/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthRegisterRoute = ApiPublicOauthRegisterRouteImport.update({
  id: '/api/public/oauth/register',
  path: '/api/public/oauth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthTokenRoute = ApiPublicOauthTokenRouteImport.update({
  id: '/api/public/oauth/token',
  path: '/api/public/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/oauth-consent': typeof AuthenticatedOauthConsentRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/characters/$id': typeof AuthenticatedCharactersIdRoute
  '/entities/$id': typeof AuthenticatedEntitiesIdRoute
  '/packs/$pack': typeof AuthenticatedPacksPackRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/characters/': typeof AuthenticatedCharactersIndexRoute
  '/packs/': typeof AuthenticatedPacksIndexRoute
  '/api/public/oauth/authorize': typeof ApiPublicOauthAuthorizeRoute
  '/api/public/oauth/register': typeof ApiPublicOauthRegisterRoute
  '/api/public/oauth/token': typeof ApiPublicOauthTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/oauth-consent': typeof AuthenticatedOauthConsentRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/characters/$id': typeof AuthenticatedCharactersIdRoute
  '/entities/$id': typeof AuthenticatedEntitiesIdRoute
  '/packs/$pack': typeof AuthenticatedPacksPackRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
  '/characters': typeof AuthenticatedCharactersIndexRoute
  '/packs': typeof AuthenticatedPacksIndexRoute
  '/api/public/oauth/authorize': typeof ApiPublicOauthAuthorizeRoute
  '/api/public/oauth/register': typeof ApiPublicOauthRegisterRoute
  '/api/public/oauth/token': typeof ApiPublicOauthTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/oauth-consent': typeof AuthenticatedOauthConsentRoute
  '/_authenticated/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/_authenticated/characters/$id': typeof AuthenticatedCharactersIdRoute
  '/_authenticated/entities/$id': typeof AuthenticatedEntitiesIdRoute
  '/_authenticated/packs/$pack': typeof AuthenticatedPacksPackRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/_authenticated/characters/': typeof AuthenticatedCharactersIndexRoute
  '/_authenticated/packs/': typeof AuthenticatedPacksIndexRoute
  '/api/public/oauth/authorize': typeof ApiPublicOauthAuthorizeRoute
  '/api/public/oauth/register': typeof ApiPublicOauthRegisterRoute
  '/api/public/oauth/token': typeof ApiPublicOauthTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/legal'
    | '/sitemap.xml'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/assistant'
    | '/dashboard'
    | '/library'
    | '/oauth-consent'
    | '/campaigns/$id'
    | '/characters/$id'
    | '/entities/$id'
    | '/packs/$pack'
    | '/api/public/mcp'
    | '/api/public/version'
    | '/campaigns/'
    | '/characters/'
    | '/packs/'
    | '/api/public/oauth/authorize'
    | '/api/public/oauth/register'
    | '/api/public/oauth/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/legal'
    | '/sitemap.xml'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/assistant'
    | '/dashboard'
    | '/library'
    | '/oauth-consent'
    | '/campaigns/$id'
    | '/characters/$id'
    | '/entities/$id'
    | '/packs/$pack'
    | '/api/public/mcp'
    | '/api/public/version'
    | '/campaigns'
    | '/characters'
    | '/packs'
    | '/api/public/oauth/authorize'
    | '/api/public/oauth/register'
    | '/api/public/oauth/token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/legal'
    | '/sitemap.xml'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/assistant'
    | '/_authenticated/dashboard'
    | '/_authenticated/library'
    | '/_authenticated/oauth-consent'
    | '/_authenticated/campaigns/$id'
    | '/_authenticated/characters/$id'
    | '/_authenticated/entities/$id'
    | '/_authenticated/packs/$pack'
    | '/api/public/mcp'
    | '/api/public/version'
    | '/_authenticated/campaigns/'
    | '/_authenticated/characters/'
    | '/_authenticated/packs/'
    | '/api/public/oauth/authorize'
    | '/api/public/oauth/register'
    | '/api/public/oauth/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LegalRoute: typeof LegalRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  ApiPublicVersionRoute: typeof ApiPublicVersionRoute
  ApiPublicOauthAuthorizeRoute: typeof ApiPublicOauthAuthorizeRoute
  ApiPublicOauthRegisterRoute: typeof ApiPublicOauthRegisterRoute
  ApiPublicOauthTokenRoute: typeof ApiPublicOauthTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oauth-consent': {
      id: '/_authenticated/oauth-consent'
      path: '/oauth-consent'
      fullPath: '/oauth-consent'
      preLoaderRoute: typeof AuthenticatedOauthConsentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/$id': {
      id: '/_authenticated/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/characters/': {
      id: '/_authenticated/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof AuthenticatedCharactersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/characters/$id': {
      id: '/_authenticated/characters/$id'
      path: '/characters/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof AuthenticatedCharactersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entities/$id': {
      id: '/_authenticated/entities/$id'
      path: '/entities/$id'
      fullPath: '/entities/$id'
      preLoaderRoute: typeof AuthenticatedEntitiesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packs/': {
      id: '/_authenticated/packs/'
      path: '/packs'
      fullPath: '/packs/'
      preLoaderRoute: typeof AuthenticatedPacksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packs/$pack': {
      id: '/_authenticated/packs/$pack'
      path: '/packs/$pack'
      fullPath: '/packs/$pack'
      preLoaderRoute: typeof AuthenticatedPacksPackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/version': {
      id: '/api/public/version'
      path: '/api/public/version'
      fullPath: '/api/public/version'
      preLoaderRoute: typeof ApiPublicVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/authorize': {
      id: '/api/public/oauth/authorize'
      path: '/api/public/oauth/authorize'
      fullPath: '/api/public/oauth/authorize'
      preLoaderRoute: typeof ApiPublicOauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/register': {
      id: '/api/public/oauth/register'
      path: '/api/public/oauth/register'
      fullPath: '/api/public/oauth/register'
      preLoaderRoute: typeof ApiPublicOauthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/token': {
      id: '/api/public/oauth/token'
      path: '/api/public/oauth/token'
      fullPath: '/api/public/oauth/token'
      preLoaderRoute: typeof ApiPublicOauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedOauthConsentRoute: typeof AuthenticatedOauthConsentRoute
  AuthenticatedCampaignsIdRoute: typeof AuthenticatedCampaignsIdRoute
  AuthenticatedCharactersIdRoute: typeof AuthenticatedCharactersIdRoute
  AuthenticatedEntitiesIdRoute: typeof AuthenticatedEntitiesIdRoute
  AuthenticatedPacksPackRoute: typeof AuthenticatedPacksPackRoute
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
  AuthenticatedCharactersIndexRoute: typeof AuthenticatedCharactersIndexRoute
  AuthenticatedPacksIndexRoute: typeof AuthenticatedPacksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedOauthConsentRoute: AuthenticatedOauthConsentRoute,
  AuthenticatedCampaignsIdRoute: AuthenticatedCampaignsIdRoute,
  AuthenticatedCharactersIdRoute: AuthenticatedCharactersIdRoute,
  AuthenticatedEntitiesIdRoute: AuthenticatedEntitiesIdRoute,
  AuthenticatedPacksPackRoute: AuthenticatedPacksPackRoute,
  AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
  AuthenticatedCharactersIndexRoute: AuthenticatedCharactersIndexRoute,
  AuthenticatedPacksIndexRoute: AuthenticatedPacksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LegalRoute: LegalRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  ApiPublicVersionRoute: ApiPublicVersionRoute,
  ApiPublicOauthAuthorizeRoute: ApiPublicOauthAuthorizeRoute,
  ApiPublicOauthRegisterRoute: ApiPublicOauthRegisterRoute,
  ApiPublicOauthTokenRoute: ApiPublicOauthTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
