UPDATE public.entities SET visibility = CASE upper(visibility)
  WHEN 'GM' THEN 'GM_ONLY'
  WHEN 'PRIVATE' THEN 'GM_ONLY'
  WHEN 'PLAYERS' THEN 'ALL_PLAYERS'
  WHEN 'SHARED' THEN 'ALL_PLAYERS'
  WHEN 'PUBLIC' THEN 'PUBLIC'
  WHEN 'GM_ONLY' THEN 'GM_ONLY'
  WHEN 'UNREVEALED' THEN 'UNREVEALED'
  WHEN 'SELECTED_PLAYERS' THEN 'SELECTED_PLAYERS'
  WHEN 'ALL_PLAYERS' THEN 'ALL_PLAYERS'
  ELSE 'GM_ONLY' END;

UPDATE public.entity_relationships SET visibility = CASE upper(visibility)
  WHEN 'GM' THEN 'GM_ONLY'
  WHEN 'PRIVATE' THEN 'GM_ONLY'
  WHEN 'PLAYERS' THEN 'ALL_PLAYERS'
  WHEN 'SHARED' THEN 'ALL_PLAYERS'
  WHEN 'PUBLIC' THEN 'PUBLIC'
  WHEN 'GM_ONLY' THEN 'GM_ONLY'
  WHEN 'UNREVEALED' THEN 'UNREVEALED'
  WHEN 'SELECTED_PLAYERS' THEN 'SELECTED_PLAYERS'
  WHEN 'ALL_PLAYERS' THEN 'ALL_PLAYERS'
  ELSE 'GM_ONLY' END;

ALTER TABLE public.entities
  ADD CONSTRAINT entities_visibility_check
  CHECK (visibility IN ('GM_ONLY','UNREVEALED','SELECTED_PLAYERS','ALL_PLAYERS','PUBLIC'));

ALTER TABLE public.entity_relationships
  ADD CONSTRAINT entity_relationships_visibility_check
  CHECK (visibility IN ('GM_ONLY','UNREVEALED','SELECTED_PLAYERS','ALL_PLAYERS','PUBLIC'));